- hosts: all
  become: true
  tasks:

  - name: Updating Packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: Installing Packages
    apt:
      pkg:
      - dnsmasq
      - hostapd
      - bc
      - build-essential
      - dkms
      - raspberrypi-kernel-headers
      - netfilter-persistent
      - iptables-persistent

  - name: Setting hostapd service
    systemd:
      name: hostapd
      masked: no
      enabled: yes

  - name: Rebooting the pi
    reboot:
  
  - name: Waiting for pi connection
    wait_for_connection:

  - name: Cloning git repo to pi
    git:
      repo: https://github.com/ScriptingChris/esp32-humidity-sensor.git
      dest: /home/pi/esp32-humidity-sensor
  
  - name: Cloning wifi drivers to pi
    git:
      repo: https://github.com/cilynx/rtl88x2bu.git
      dest: /home/pi/drivers
  
  - name: Installing wifi drivers
    shell: |
      sed -i 's/I386_PC = y/I386_PC = n/' Makefile
      sed -i 's/ARM_RPI = n/ARM_RPI = y/' Makefile
      VER=$(sed -n 's/\PACKAGE_VERSION="\(.*\)"/\1/p' dkms.conf)
      sudo rsync -rvhP ./ /usr/src/rtl88x2bu-${VER}
      sudo dkms add -m rtl88x2bu -v ${VER}
      sudo dkms build -m rtl88x2bu -v ${VER}
      sudo dkms install -m rtl88x2bu -v ${VER}
    args:
      chdir: /home/pi/drivers/
    
  - name: Creating the /etc/sysctl.d/routed-ap.conf
    file:
      path: /etc/sysctl.d/routed-ap.conf
      state: touch

  - name: Configuring Wifi
    shell: |
      sudo tee -a /etc/dhcpcd.conf <<EOF
      interface wlan1
          static ip_address=192.168.99.1/24
          nohook wpa_supplicant
      EOF

      sudo tee /etc/systcl.d/routed-ap.conf <<EOF
      net.ipv4.ip_forward=1
      EOF

      sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE

      sudo netfilter-persistent save

      sudo tee /etc/dnsmasq.conf <<EOF
      interface=wlan1
        dhcp-range=192.168.99.100,192.168.99.199,255.255.255.0,24h
        domain=wlan
        address=/rt.wlan/192.168.99.1
      EOF

      sudo tee /etc/hostapd/hostapd.conf <<EOF
      interface=wlan1
      driver=nl80211
      ssid=pinet
      hw_mode=a
      channel=36
      wmm_enabled=0
      macaddr_acl=0
      auth_algs=1
      ignore_broadcast_ssid=0
      wpa=2
      wpa_passphrase=P!ssw0rd1234
      wpa_key_mgmt=WPA-PSK
      wpa_pairwise=TKIP
      rsn_pairwise=CCMP
      EOF

  - name: Rebooting the pi
    reboot:
  
  - name: Waiting for pi connection
    wait_for_connection: